// Generated by Apple Swift version 2.3 (swiftlang-800.10.13 clang-800.0.42.1)
#pragma clang diagnostic push

#if defined(__has_include) && __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#include <objc/NSObject.h>
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if defined(__has_include) && __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus) || __cplusplus < 201103L
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif

#if defined(__has_attribute) && __has_attribute(objc_runtime_name)
# define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
#else
# define SWIFT_RUNTIME_NAME(X)
#endif
#if defined(__has_attribute) && __has_attribute(swift_name)
# define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
#else
# define SWIFT_COMPILE_NAME(X)
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA
#endif
#if !defined(SWIFT_CLASS)
# if defined(__has_attribute) && __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif

#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif

#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif

#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if defined(__has_attribute) && __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name) enum _name : _type _name; enum SWIFT_ENUM_EXTRA _name : _type
# if defined(__has_feature) && __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME) SWIFT_ENUM(_type, _name)
# endif
#endif
#if defined(__has_feature) && __has_feature(modules)
@import UIKit;
@import ObjectiveC;
@import Foundation;
@import WebKit;
#endif

#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
@class NSBundle;
@class NSCoder;

SWIFT_CLASS("_TtC13PianoComposer23BasePopupViewController")
@interface BasePopupViewController : UIViewController
- (void)viewDidLoad;
- (void)show;
- (void)close;
- (void)viewDidLayoutSubviews;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13PianoComposer12CustomParams")
@interface CustomParams : NSObject
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull content;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull user;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull request;
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end

enum DelayType : NSInteger;

SWIFT_CLASS("_TtC13PianoComposer7DelayBy")
@interface DelayBy : NSObject
@property (nonatomic, readonly) enum DelayType type;
@property (nonatomic, readonly) NSInteger value;
@end

typedef SWIFT_ENUM(NSInteger, DelayType) {
  DelayTypetime = 0,
  DelayTypescroll = 1,
};

typedef SWIFT_ENUM(NSInteger, DisplayMode) {
  DisplayModeinline = 0,
  DisplayModemodal = 1,
};

@class XpAccessItem;
@class User;

SWIFT_CLASS("_TtC13PianoComposer28ExperienceExecuteEventParams")
@interface ExperienceExecuteEventParams : NSObject
@property (nonatomic, readonly, copy) NSArray<XpAccessItem *> * _Nonnull accessList;
@property (nonatomic, readonly, strong) User * _Nullable user;
@end


SWIFT_CLASS("_TtC13PianoComposer18FailureEventParams")
@interface FailureEventParams : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleId;
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleType;
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleName;
@property (nonatomic, readonly, copy) NSString * _Nonnull errorMessage;
@end


SWIFT_CLASS("_TtC13PianoComposer5Meter")
@interface Meter : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull meterName;
@property (nonatomic, readonly) NSInteger views;
@property (nonatomic, readonly) NSInteger viewsLeft;
@property (nonatomic, readonly) NSInteger maxViews;
@property (nonatomic, readonly) NSInteger totalViews;
- (NSDictionary<NSString *, id> * _Nonnull)toDictionary;
@end


@interface NSDate (SWIFT_EXTENSION(PianoComposer))
- (int64_t)toUnixTimestamp;
@end


SWIFT_CLASS("_TtC13PianoComposer24PageViewMeterEventParams")
@interface PageViewMeterEventParams : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull meterName;
@property (nonatomic, readonly) NSInteger views;
@property (nonatomic, readonly) NSInteger viewsLeft;
@property (nonatomic, readonly) NSInteger maxViews;
@property (nonatomic, readonly) NSInteger totalViews;
@end

@protocol PianoComposerDelegate;

SWIFT_CLASS("_TtC13PianoComposer13PianoComposer")
@interface PianoComposer : NSObject
+ (NSString * _Nonnull)tinypassEndpointUrl;
+ (NSString * _Nonnull)sandboxEndpointUrl;
+ (NSString * _Nonnull)tinypassUserProviderName;
+ (NSString * _Nonnull)janrainUserProviderName;
@property (nonatomic, weak) id <PianoComposerDelegate> _Nullable delegate;
@property (nonatomic, readonly, copy) NSString * _Nonnull aid;
@property (nonatomic, readonly) NSInteger protocolVersion;
@property (nonatomic, readonly, copy) NSString * _Nonnull submitType;
@property (nonatomic, copy) NSString * _Nonnull endpointUrl;
@property (nonatomic, copy) NSSet<NSString *> * _Nonnull tags;
@property (nonatomic, copy) NSDictionary<NSString *, id> * _Nonnull customVariables;
@property (nonatomic, strong) CustomParams * _Nullable customParams;
@property (nonatomic, copy) NSString * _Nonnull url;
@property (nonatomic, copy) NSString * _Nonnull referrer;
@property (nonatomic, copy) NSString * _Nonnull zoneId;
@property (nonatomic) BOOL debug;
@property (nonatomic, copy) NSString * _Nonnull userToken;
@property (nonatomic, copy) NSString * _Nonnull contentCreated;
@property (nonatomic, copy) NSString * _Nonnull contentAuthor;
@property (nonatomic, copy) NSString * _Nonnull contentSection;
@property (nonatomic, copy) NSString * _Nonnull gaClientId;
- (nonnull instancetype)initWithAid:(NSString * _Nonnull)aid endpointUrl:(NSString * _Nonnull)endpointUrl OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithAid:(NSString * _Nonnull)aid;
- (nonnull instancetype)initWithAid:(NSString * _Nonnull)aid sandbox:(BOOL)sandbox;
- (PianoComposer * _Nonnull)endpointUrl:(NSString * _Nonnull)endpointUrl;
- (PianoComposer * _Nonnull)tag:(NSString * _Nonnull)tag;
- (PianoComposer * _Nonnull)tags:(NSArray<NSString *> * _Nonnull)tagCollection;
- (PianoComposer * _Nonnull)customVariable:(NSString * _Nonnull)name value:(id _Nonnull)value;
- (PianoComposer * _Nonnull)customVariables:(NSDictionary<NSString *, id> * _Nonnull)customVariableCollection;
- (PianoComposer * _Nonnull)customParams:(CustomParams * _Nonnull)customParams;
- (PianoComposer * _Nonnull)url:(NSString * _Nonnull)url;
- (PianoComposer * _Nonnull)userToken:(NSString * _Nonnull)userToken;
- (PianoComposer * _Nonnull)referrer:(NSString * _Nonnull)referrer;
- (PianoComposer * _Nonnull)zoneId:(NSString * _Nonnull)zoneId;
- (PianoComposer * _Nonnull)debug:(BOOL)debug;
- (PianoComposer * _Nonnull)contentCreated:(NSString * _Nonnull)contentCreated;
- (PianoComposer * _Nonnull)contentAuthor:(NSString * _Nonnull)contentAuthor;
- (PianoComposer * _Nonnull)contentSection:(NSString * _Nonnull)contentSection;
- (PianoComposer * _Nonnull)delegate:(id <PianoComposerDelegate> _Nullable)delegate;
- (PianoComposer * _Nonnull)gaClientId:(NSString * _Nonnull)gaClientId;

/// Start experiences executing
- (PianoComposer * _Nonnull)execute;
@end

@class XpEvent;
@class ShowLoginEventParams;
@class ShowTemplateEventParams;

SWIFT_PROTOCOL("_TtP13PianoComposer21PianoComposerDelegate_")
@protocol PianoComposerDelegate
@optional

/// Show login event
- (void)showLogin:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event params:(ShowLoginEventParams * _Nullable)params;

/// Show template event
- (void)showTemplate:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event params:(ShowTemplateEventParams * _Nullable)params;

/// Non site action event
- (void)nonSite:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event;

/// User segment true event
- (void)userSegmentTrue:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event;

/// User segment false event
- (void)userSegmentFalse:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event;

/// Meter active event
- (void)meterActive:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event params:(PageViewMeterEventParams * _Nullable)params;

/// Meter expired event
- (void)meterExpired:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event params:(PageViewMeterEventParams * _Nullable)params;

/// Exeperience execution failed
- (void)experienceExecutionFailed:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event params:(FailureEventParams * _Nullable)params;

/// Exeperience execute event
- (void)experienceExecute:(PianoComposer * _Nonnull)composer event:(XpEvent * _Nonnull)event params:(ExperienceExecuteEventParams * _Nullable)params;
@required

/// Event fired by composer when async task was completed and all experience event fired
- (void)composerExecutionCompleted:(PianoComposer * _Nonnull)composer;
@end

@protocol PianoShowTemplateDelegate;

SWIFT_CLASS("_TtC13PianoComposer27PianoShowTemplateController")
@interface PianoShowTemplateController : NSObject
@property (nonatomic, weak) id <PianoShowTemplateDelegate> _Nullable delegate;
@property (nonatomic, strong) ShowTemplateEventParams * _Nonnull params;
- (nonnull instancetype)initWithParams:(ShowTemplateEventParams * _Nonnull)params OBJC_DESIGNATED_INITIALIZER;
- (void)show;
@end

@class WKUserContentController;
@class WKScriptMessage;

@interface PianoShowTemplateController (SWIFT_EXTENSION(PianoComposer)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class UIView;

SWIFT_PROTOCOL("_TtP13PianoComposer25PianoShowTemplateDelegate_")
@protocol PianoShowTemplateDelegate
- (UIView * _Nullable)findViewBySelector:(NSString * _Nonnull)selector;
@optional
- (void)onCustomEvent:(id _Nonnull)eventData;
- (void)onClose:(id _Nonnull)eventData;
- (void)onCloseAndRefresh:(id _Nonnull)eventData;
- (void)onRegister:(id _Nonnull)eventData;
- (void)onLogin:(id _Nonnull)eventData;
- (void)onLogout:(id _Nonnull)eventData;
@end

@class WKWebView;
@class UIActivityIndicatorView;

SWIFT_CLASS("_TtC13PianoComposer36PianoShowTemplatePopupViewController")
@interface PianoShowTemplatePopupViewController : BasePopupViewController
@property (nonatomic, strong) WKWebView * _Null_unspecified webView;
@property (nonatomic, strong) UIActivityIndicatorView * _Null_unspecified activityIndicator;
@property (nonatomic, strong) ShowTemplateEventParams * _Nonnull showTemplateParams;
@property (nonatomic, weak) id <PianoShowTemplateDelegate> _Nullable delegate;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)initWithParams:(ShowTemplateEventParams * _Nonnull)params OBJC_DESIGNATED_INITIALIZER;
- (void)viewDidLoad;
- (void)viewWillLayoutSubviews;
- (void)viewWillAppear:(BOOL)animated;
- (void)viewDidAppear:(BOOL)animated;
- (void)close;
@end


@interface PianoShowTemplatePopupViewController (SWIFT_EXTENSION(PianoComposer)) <WKScriptMessageHandler>
- (void)userContentController:(WKUserContentController * _Nonnull)userContentController didReceiveScriptMessage:(WKScriptMessage * _Nonnull)message;
@end

@class WKNavigation;
@class NSError;
@class WKNavigationAction;

@interface PianoShowTemplatePopupViewController (SWIFT_EXTENSION(PianoComposer)) <WKNavigationDelegate>
- (void)webView:(WKWebView * _Nonnull)webView didFailNavigation:(WKNavigation * _Null_unspecified)navigation withError:(NSError * _Nonnull)error;
- (void)webView:(WKWebView * _Nonnull)webView decidePolicyForNavigationAction:(WKNavigationAction * _Nonnull)navigationAction decisionHandler:(void (^ _Nonnull)(WKNavigationActionPolicy))decisionHandler;
- (void)webView:(WKWebView * _Nonnull)webView didFinishNavigation:(WKNavigation * _Null_unspecified)navigation;
@end


SWIFT_CLASS("_TtC13PianoComposer20ShowLoginEventParams")
@interface ShowLoginEventParams : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull userProvider;
@end


SWIFT_CLASS("_TtC13PianoComposer23ShowTemplateEventParams")
@interface ShowTemplateEventParams : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull templateId;
@property (nonatomic, readonly) enum DisplayMode displayMode;
@property (nonatomic, readonly, strong) DelayBy * _Nullable delayBy;
@property (nonatomic, readonly, copy) NSString * _Nonnull containerSelector;
@property (nonatomic, readonly) BOOL showCloseButton;
@end


SWIFT_CLASS("_TtC13PianoComposer14SplitTestEntry")
@interface SplitTestEntry : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull splitTestVariantId;
@property (nonatomic, readonly, copy) NSString * _Nonnull splitTestVariantName;
- (nonnull instancetype)initWithDict:(NSDictionary<NSString *, id> * _Nonnull)dict OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13PianoComposer4User")
@interface User : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull uid;
@property (nonatomic, readonly, copy) NSString * _Nonnull firstName;
@property (nonatomic, readonly, copy) NSString * _Nonnull lastName;
@property (nonatomic, readonly, copy) NSString * _Nonnull email;
@end


SWIFT_CLASS("_TtC13PianoComposer12XpAccessItem")
@interface XpAccessItem : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull rid;
@property (nonatomic, readonly, copy) NSString * _Nonnull resourceName;
@property (nonatomic, readonly) int64_t expireDate;
@property (nonatomic, readonly) int64_t daysUntilExpiration;
- (nonnull instancetype)initWithDict:(NSDictionary<NSString *, id> * _Nonnull)dict OBJC_DESIGNATED_INITIALIZER;
@end

@class XpEventModuleParams;
@class XpEventExecutionContext;

SWIFT_CLASS("_TtC13PianoComposer7XpEvent")
@interface XpEvent : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull eventType;
@property (nonatomic, readonly, strong) XpEventModuleParams * _Nullable eventModuleParams;
@property (nonatomic, readonly, strong) XpEventExecutionContext * _Nullable eventExecutionContext;
- (nonnull instancetype)initWithDict:(NSDictionary<NSString *, id> * _Nonnull)dict OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13PianoComposer23XpEventExecutionContext")
@interface XpEventExecutionContext : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull experienceId;
@property (nonatomic, readonly, copy) NSString * _Nonnull executionId;
@property (nonatomic, readonly, copy) NSString * _Nonnull trackingId;
@property (nonatomic, readonly, copy) NSArray<SplitTestEntry *> * _Nonnull splitTestEntries;
@property (nonatomic, readonly, copy) NSString * _Nonnull currentMeterName;
@property (nonatomic, readonly, strong) User * _Nullable user;
@property (nonatomic, readonly, copy) NSString * _Nonnull region;
@property (nonatomic, readonly, copy) NSString * _Nonnull countryCode;
@property (nonatomic, readonly, copy) NSArray<XpAccessItem *> * _Nonnull accessList;
@property (nonatomic, readonly, copy) NSArray<Meter *> * _Nonnull activeMeters;
- (nonnull instancetype)initWithDict:(NSDictionary<NSString *, id> * _Nonnull)dict OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC13PianoComposer19XpEventModuleParams")
@interface XpEventModuleParams : NSObject
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleId;
@property (nonatomic, readonly, copy) NSString * _Nonnull moduleName;
- (nonnull instancetype)initWithDict:(NSDictionary<NSString *, id> * _Nonnull)dict OBJC_DESIGNATED_INITIALIZER;
@end

#pragma clang diagnostic pop
