# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SampleSwiftApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleSwiftApp
  pod 'PianoComposer', '~> 2.3.9'
  pod 'PianoOAuth', '~> 2.3.9'
end
